# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'IOS-Demo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS-Demo
  pod 'Firebase', '~> 3.5'
  pod 'Firebase/Auth'
  pod 'FirebaseAuth', '~> 3.0'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

end
